#!/bin/bash

# Nombre del contenedor Docker que ejecuta el servidor de Minecraft
DOCKER_CONTAINER="138"

# Frases predefinidas
FRASES=(
"%s, cabrón, eres tan malo que hasta los esqueletos te disparan por compasión."
"%s, desinstala el juego, inútil, que das más pena que un cerdo sin montura."
"%s, ¿eres tan lento o es que te minaron el cerebro con TNT?"
"%s, pedazo de mierda, ni con un pico de diamante sacas algo decente."
"%s, eres el rey de los noobs, hasta los pollitos te mean encima."
"%s, hijo de puta, juega con los ojos abiertos o vete a FarmVille."
"%s, ¿te costó mucho ser tan paquete o te sale natural?"
"%s, cabronazo, hasta las ovejas te esquilan a ti de lo malo que eres."
"%s, quítate del server, que ocupas espacio y no sirves pa’ nada."
"%s, inútil, ni con un mapa encuentras el camino a ser bueno."
"%s, ¿qué haces jugando? Si hasta los slimes te resbalan de lo patético."
"%s, eres tan malo que el Ender Dragon se ríe de ti antes de matarte."
"%s, cabrón, deja de morir, que gastas más vidas que un gato."
"%s, paquete, ni con un elytra levantas el vuelo, perdedor."
"%s, ¿te llamas minero o es que solo sabes cavar tu propia vergüenza?"
"%s, hijo de puta, hasta los ghasts lloran de lo mal que lo haces."
"%s, eres tan inútil que te ahogas en un charco de una cuadra."
"%s, cabronazo, juega con tutoriales de YouTube a ver si aprendes algo."
"%s, ¿tan malo eres o es que tu teclado está en braille?"
"%s, pedazo de mierda, ni las arañas te quieren en su red."
"%s, desinstala ya, que das más lástima que un aldeano sin trabajo."
"%s, inútil, si sigues así te baneo por ser un peligro público."
"%s, cabrón, hasta los lobos te abandonan por noob."
"%s, ¿qué haces jugando si ni el crafting básico te sale, inútil?"
"%s, eres tan lento que te pilla un zombi bebito sin correr."
"%s, hijo de puta, ni con un beacon brillas en este juego."
"%s, paquete, deja de romper bloques que rompes el server de lo malo."
"%s, cabronazo, hasta el Wither te deja vivo por pena."
"%s, ¿te mataron otra vez? Normal, si juegas con los ojos cerrados."
"%s, inútil, vete a practicar con los niños de preescolar."
"%s, cabrón, eres tan malo que te kickea un aldeano enfadado."
"%s, pedazo de mierda, ni con mods mejoras, desastre."
"%s, ¿qué haces vivo todavía? Si hasta las vacas te dan cornadas."
"%s, hijo de puta, juega en creativo a ver si así no mueres tanto."
"%s, eres tan noob que confundes un pico con una espada."
"%s, cabronazo, deja de cavar recto abajo, inútil de mierda."
"%s, paquete, ni con un totem de inmortalidad duras dos minutos."
"%s, ¿te gusta perder o es que no sabes ni dónde está el botón de salir?"
"%s, inútil, hasta los endermans te ignoran de lo irrelevante que eres."
"%s, cabrón, juega en paz o vete a criar flores, perdedor."
"%s, pedazo de mierda, ni con trampas ganas, qué triste."
"%s, hijo de puta, te matan más rápido que un cerdo en lava."
"%s, eres tan malo que te banean por error pensando que haces trampa."
"%s, cabronazo, deja de alimentar a los zombis con tu cadaver."
"%s, inútil, ni con un stack de manzanas doradas sobrevives."
"%s, ¿qué haces jugando si ni sabes romper un árbol?"
"%s, paquete, te mueres tanto que el respawn te tiene en favoritos."
"%s, cabrón, hasta los aldeanos te roban por lo tonto que eres."
"%s, pedazo de mierda, vete a jugar al Roblox, esto te queda grande."
"%s, hijo de puta, ni con un escudo bloqueas tu inutilidad."
"%s, eres tan lento que te pilla una tortuga coja."
"%s, cabronazo, deja de morir en la primera noche, inútil."
"%s, ¿te gusta el fondo del mar o por eso te ahogas tanto?"
"%s, paquete, ni con un caballo llegas lejos, perdedor."
"%s, inútil, te matan más veces que bloques hay en el juego."
"%s, cabrón, juega en modo espectador, total, no haces nada."
"%s, pedazo de mierda, hasta los pillagers te tienen lástima."
"%s, hijo de puta, ni con un tridente te salvas del agua."
"%s, eres tan malo que te kickean por ser un NPC."
"%s, cabronazo, vete a construir casas de tierra, es lo tuyo."
"%s, inútil, si sigues así te hago spawn en el Nether sin armadura."
"%s, ¿qué haces jugando si ni sabes qué es un lingote?"
"%s, paquete, te matan tan rápido que ni lo ves venir."
"%s, cabrón, deja de perder el tiempo y el nuestro, noob."
"%s, pedazo de mierda, ni con un faro encuentras el camino."
"%s, hijo de puta, te caes más que un aldeano sin escalera."
"%s, eres tan inútil que te matan con una patata envenenada."
"%s, cabronazo, juega en fácil y aun así das pena."
"%s, ¿te mató un conejo? Normal, si eres un desastre."
"%s, paquete, ni con un arco das a un bloque a dos pasos."
"%s, inútil, vete a cavar arena, es lo único que sabes hacer."
"%s, cabrón, hasta los gatos te bufan de lo malo que eres."
"%s, pedazo de mierda, te mueres más que un aldeano en raid."
"%s, hijo de puta, ni con un encantamiento mejoras tu vida."
"%s, eres tan lento que te adelanta un caracol con resaca."
"%s, cabronazo, deja de dar excusas, eres un puto noob."
"%s, inútil, te matan y ni sabes de dónde vino el golpe."
"%s, ¿qué haces jugando si tu casa es un cubo de tierra?"
"%s, paquete, ni con un portal al Nether encuentras la salida."
"%s, cabrón, te kickeo yo mismo por ser tan mierda."
"%s, pedazo de mierda, hasta los shulkers te escupen por asco."
"%s, hijo de puta, juega con un mando roto y mejoras."
"%s, eres tan malo que te banean por ser un bug."
"%s, cabronazo, deja de morir por lava, aprende a saltar."
"%s, inútil, ni con una brújula encuentras tu dignidad."
"%s, ¿te gusta el respawn o por eso vives ahí?"
"%s, paquete, te matan más rápido que un speedrunner."
"%s, cabrón, vete a mirar streams, esto no es lo tuyo."
"%s, pedazo de mierda, ni con un yunque te aplastan la noobez."
"%s, hijo de puta, te mueres tanto que el chat es tu obituario."
"%s, eres tan inútil que te pilla un golem sin moverte."
"%s, cabronazo, juega en creativo y aún pierdes items."
"%s, ¿qué haces vivo si ni sabes hacer una fogata?"
"%s, paquete, te matan con un puñetazo sin armadura."
"%s, inútil, vete a criar pollos, es lo único que no matas."
"%s, cabrón, hasta los drowned te dan ventaja y pierdes."
"%s, pedazo de mierda, ni con un escudo te salvas de ti mismo."
"%s, hijo de puta, te caes al vacío con un elytra puesto."
"%s, eres tan malo que te banean por ser un meme."
"%s, cabronazo, desinstala Minecraft y dedicate al parchís."
"%s, ¿te perdiste otra vez o es que te gusta explorar el vacío?"
"%s, amigo, ese pico no cava solo, ¡dale caña!"
"%s, ¿eres minero o estás practicando para los Juegos Olímpicos de caerte?"
"%s, te veo más perdido que un aldeano en el Nether."
"%s, ¿cuándo aprendes a no morir en la primera noche, campeón?"
"%s, esa casa de tierra está gritando ‘arquitecto novato’."
"%s, ¿te mató un creeper o solo querías un abrazo explosivo?"
"%s, colega, deja de alimentar a los zombis con tus drops."
"%s, ¿tanto te gusta la lava o es que buscas un spa caliente?"
"%s, ese golpe al árbol parecía más un masaje que un puñetazo."
"%s, ¿eres lento o es que el juego va en cámara lenta contigo?"
"%s, amigo, hasta los lobos te miran como diciendo ‘¿en serio?’"
"%s, ¿te costó mucho construir ese cubo o fue improvisado?"
"%s, parece que los esqueletos te quieren más que nosotros."
"%s, ¿te caíste al vacío o estabas probando un salto épico?"
"%s, ese equipo de madera grita ‘recién llegado’."
"%s, colega, deja de correr en círculos, ¡no es una maratón!"
"%s, ¿te mataron o solo te tomaste un descanso sorpresa?"
"%s, ese crafting parece arte abstracto, ¡sigue intentándolo!"
"%s, ¿eres minero o estás buscando un tesoro imaginario?"
"%s, amigo, los endermans te esquivan por pura cortesía."
"%s, ¿te gusta el respawn o es que te sientes como en casa ahí?"
"%s, esa armadura de cuero está pidiendo un upgrade, ¿no crees?"
"%s, ¿te persiguen los zombis o solo quieren ser tus fans?"
"%s, colega, deja de cavar recto abajo, ¡no es un atajo!"
"%s, ¿te mató un slime o solo te dio un abrazo pegajoso?"
"%s, ese faro que no usas dice mucho de tu sentido de la orientación."
"%s, amigo, parece que los creepers te tienen cariño especial."
"%s, ¿tanto te gusta el Nether o es que extrañas el calor?"
"%s, esa espada parece más un cuchillo de mantequilla."
"%s, ¿te perdiste el tutorial o es que improvisas como genio?"
"%s, colega, los aldeanos te miran como diciendo ‘¿qué haces?’"
"%s, ¿te mataron otra vez o es tu manera de saludar?"
"%s, ese puente de un bloque es un reto personal, ¿verdad?"
"%s, amigo, deja de morir por lava, ¡no es una piscina!"
"%s, ¿eres lento o es que disfrutas el paisaje a tu ritmo?"
"%s, esa base parece un work in progress eterno."
"%s, ¿te gusta el fondo del mar o por eso te ahogas tanto?"
"%s, colega, hasta las ovejas te miran con cara de ‘venga ya’."
"%s, ¿te mató un esqueleto o solo le diste ventaja?"
"%s, ese pico de piedra dice ‘no me esfuerzo mucho’."
"%s, amigo, parece que el Wither te tiene de mascota."
"%s, ¿te caíste o estabas practicando un parkour secreto?"
"%s, esa fogata parece más un intento que un éxito."
"%s, ¿tanto te gustan los zombis o es que buscas amigos?"
"%s, colega, deja de perder el caballo, ¡no es un GPS!"
"%s, ¿te mataron o solo querías probar el respawn?"
"%s, ese arco dispara más despacio que una tortuga."
"%s, amigo, los pillagers te invitan a sus fiestas, ¿no?"
"%s, ¿eres minero o solo te gusta el eco de las cuevas?"
"%s, esa armadura grita ‘mejoraré algún día’."
"%s, ¿te persigue un ghast o solo quiere charlar?"
"%s, colega, deja de romper bloques al azar, ¡haz un plan!"
"%s, ¿te mató un drowned o solo querías nadar con él?"
"%s, amigo, parece que el Ender Dragon te tiene de sparring."
"%s, ¿te gusta cavar o es que buscas un récord personal?"
"%s, ese cofre desorganizado es tu marca personal."
"%s, ¿te caíste al lava o estabas probando un baño caliente?"
"%s, colega, los slimes te quieren más que nosotros."
"%s, ¿tanto te gusta morir o es que practicas para algo?"
"%s, amigo, ese elytra parece más decoración que utilidad."
"%s, ¿te mataron o solo estabas saludando al enemigo?"
"%s, esa casa de madera dice ‘principiante con estilo’."
"%s, ¿eres lento o es que disfrutas cada bloque del camino?"
"%s, colega, deja de perder la brújula, ¡no es un souvenir!"
"%s, ¿te gusta el Nether o es que te sientes como en casa?"
"%s, amigo, parece que los zombis te adoptaron."
"%s, ¿te mató un conejo o solo te dio un sustito?"
"%s, esa pala parece más un recuerdo que una herramienta."
"%s, ¿te perdiste o es que exploras a tu manera?"
"%s, colega, deja de caer en trampas, ¡usa los ojos!"
"%s, ¿te mataron o solo querías un descanso VIP?"
"%s, amigo, ese totem parece más un adorno que un salvavidas."
"%s, ¿tanto te gustan las arañas o es que buscas telarañas?"
"%s, esa base es un ‘work in progress’ eterno, ¿no?"
"%s, ¿te persigue un esqueleto o solo quiere ser tu compi?"
"%s, colega, parece que los creepers te siguen por diversión."
"%s, ¿te mató un golem o solo le diste un abrazo?"
"%s, amigo, ese arco dispara como si tuviera sueño."
"%s, ¿eres minero o solo te gusta el sonido del pico?"
"%s, esa armadura de hierro dice ‘voy mejorando’."
"%s, ¿te caíste al vacío o estabas probando gravedad?"
"%s, colega, deja de morir en el mismo sitio, ¡cambia de ruta!"
"%s, ¿te mataron o solo estabas haciendo amigos nuevos?"
"%s, amigo, parece que los endermans te tienen manía."
"%s, ¿tanto te gusta la lava o es que buscas un récord?"
"%s, ese cofre lleno de basura es tu firma personal."
"%s, ¿te persigue un zombi o solo quiere un autógrafo?"
"%s, colega, deja de romper el árbol a puñetazos lentos."
"%s, ¿te mató un slime o solo te dio un besito viscoso?"
"%s, amigo, esa casa grita ‘me esfuerzo, pero poco’."
"%s, ¿eres lento o es que el juego te da tiempo para pensar?"
"%s, ¿te caíste o estabas ensayando un salto épico?"
"%s, colega, parece que los aldeanos te quieren de líder."
"%s, ¿te mataron o solo querías probar el suelo?"
"%s, amigo, ese pico de madera es tu amuleto de la suerte."
"%s, ¿tanto te gusta el respawn o es tu segunda casa?"
"%s, ¿te persigue un ghast o solo quiere jugar contigo?"
"%s, colega, deja de perder el mapa, ¡no es un coleccionable!"
"%s, ¿te mató un creeper o solo fue un susto amistoso?"
"%s, illo, ¿tú juega o qué? Que eres má malo que un dolor de muela."
"%s, vente pa Torremolino conmigo, que nos tomamo una servesa y te enseño a picá piedra."
"%s, ¿qué pasa, tronco? Que te pegan los creeper y ni te enteras, ¡jartible!"
"%s, illo, eres tan lento que te pilla un zombie cojo en chancla."
"%s, ¡vaya tela contigo! Esto no es Minecraft, esto es pa ti Minecaca."
"%s, ¿tú ha construío eso? Si parece un chabolo de la Línea, ¡qué arte!"
"%s, illo, déjate de pico y pala y vámono a comerno un pescaíto frito."
"%s, eres má torpe que un guiri bailando flamenco, ¡vaya cuadro!"
"%s, ¿esa armadura? Si con eso no te salva ni la Macarena, ¡olvidah!"
"%s, illo, te ha explota el TNT en la cara, ¡qué salero tiene el niño!"
"%s, vente pa Málaga, que te invito a un espeto y te quito esa cara de panoli."
"%s, ¿qué haces, loco? Que te ha matao un esqueleto con un ojo cerrao."
"%s, illo, tú no juega, tú hace el parguela con los bloques, ¡vaya tela!"
"%s, si sigue así te llevo a la Feria de Abril pa que aprenda a sobreviví."
"%s, ¿esa base? Si eso lo hace mi primo el Chico con un cubata en la mano."
"%s, illo, eres má malo que el lag en un server de Almería, ¡qué fatiga!"
"%s, vente pa Cádiz, que con ese nivel no te quieren ni los zombi."
"%s, ¿tú sabe cavá o qué? Que te entierran los ghast con dos lagrimita."
"%s, illo, ponte las pila, que te da pal pelo hasta un pollo del juego."
"%s, ¿eso es un pico de diamante? Si con eso no corta ni un pescaíto."
"%s, vámono pa la playa de Huelva, que aquí no das pie con bola, ¡jartá!"
"%s, illo, te ha pillao el Ender Dragon y ni te ha mirao, ¡qué arte!"
"%s, tú no juega a Minecraft, tú juega a hacer el ridículo, ¡venga ya!"
"%s, vente pa Sevilla, que te meto en la Giralda pa que espabile."
"%s, ¿qué pasa, primo? Que te explota un creeper y te quedas tan pancho."
"%s, illo, con ese nivel te mando a Jerez a aprendé de los caballo."
"%s, ¿tú ha visto esa casa? Si parece un cortijo abandonao, ¡qué malaje!"
"%s, vente pa Granada, que nos tomamo una Alhambra y te quito el susto."
"%s, eres tan paquete que te mata un slime con resaca, ¡vaya tela!"
"%s, illo, si sigue así te llevo a la Alpujarra a criá cabra, ¡mejor!"
"%s, ¿qué haces, loco? Que te ha dao un zombie con un brick de leche."
"%s, vente pa Algeciras, que con ese juego no te quiere ni el viento."
"%s, illo, ponte serio, que te pilla un piglin y te roba hasta los gayumbos."
"%s, ¿esa espada? Si con eso no corta ni un flamenquín, ¡apañao va!"
"%s, tú no cava, tú hace un hoyo pa caerte dentro, ¡qué salero!"
"%s, vente pa Córdoba, que te meto en la Mezquita a rezá pa mejora."
"%s, illo, eres má inútil que un golem de hierro sin pueblo, ¡vaya tela!"
"%s, ¿tú juega o mira? Que te ha matao un phantom con sueño."
"%s, vámono pa Jaén, que con ese nivel te hago un castillo de aceite."
"%s, illo, te ha explota la cara un creeper, ¡qué arte tienes, loco!"
"%s, ¿esa mina? Si parece un zulo de la abuela, ¡qué mal fario!"
"%s, vente pa Ronda, que te tiro por el tajo pa que espabile, ¡venga!"
"%s, illo, con ese juego te mando a la Rocío a pedí un milagro."
"%s, ¿tú ha hecho eso? Si parece un chiringuito cerrao, ¡qué malaje!"
"%s, eres tan malo que te pilla un drowned con un flotador, ¡jartible!"
"%s, vente pa Marbella, que con ese nivel te hago un yate de madera."
"%s, illo, te ha dao un blaze y ni te ha apuntao, ¡qué salero!"
"%s, ¿qué pasa, tronco? Que te pierdes en el Nether como turista."
"%s, tú no juega a Minecraft, tú juega a dar penita, ¡vaya tela!"
"%s, illo, vámono pa la Costa del Sol, que aquí no das una, ¡apañao!"
"LAS PAREDES ME MIRAN JODER Y NO PARAN DE REÍRSE DE MÍ"
"AQUÍ NO HAY SOL SOLO BLOQUES Y UN ECO QUE ME GRITA PERDEDOR"
"HE VISTO UN CREEPER Y ME HA GUIÑADO UN OJO ESTOY ACABADO"
"MIS MANOS TIEMBLAN EL PICO SE RÍE Y LA LAVA ME SUSURRA COSAS RARAS"
"TRES DÍAS CAVANDO Y LO ÚNICO QUE ENCONTRÉ FUE MI PROPIA SOMBRA"
"EL SERVIDOR ME ODIA LO NOTO EN CÓMO CAEN LAS ANTORCHAS AL SUELO"
"UN ZOMBIE ME HA TOSIDO ENCIMA Y CREO QUE ME HA CONTAGIADO LA LOCURA"
"ESTAS CUATRO PAREDES DE PIEDRA ME CANTAN COPLAS TRISTES POR LA NOCHE"
"HE HABLADO CON UN ESQUELETO Y ME HA DICHO QUE ME RINDA YA"
"LA OSCURIDAD ME ABRAZA Y HUELE A PODRIDO NO AGUANTO MÁS"
"LOS BLOQUES SE MUEVEN SOLOS LO JURO ESTE SITIO ESTÁ VIVO"
"MI REFLEJO EN EL AGUA ME HA DICHO QUE ME TIRE QUÉ HAGO"
"HE GRITADO Y EL ECO ME HA CONTESTADO CÁLLATE INÚTIL"
"LA MADERA CRUJE COMO SI ME ESTUVIERA JUZGANDO QUÉ MIERDA ES ESTA"
"UN POLLO ME HA MIRADO MAL Y AHORA NO DUERMO ESTOY PERDIENDO LA CABEZA"
"CAVÉ TAN HONDO QUE OÍ MI PROPIA VOZ PIDIÉNDOME QUE PARARA"
"ESTE SERVIDOR ES UNA JAULA Y YO SOY EL LOCO QUE LA ROMPIÓ"
"LA LAVA BURBUJEA Y ME DICE QUE SALTE QUÉ CALOR TAN CABRÓN"
"HE VISTO UN DIAMANTE Y SE HA REÍDO DE MÍ ANTES DE DESAPARECER"
"MIS OJOS ARDEN LAS ANTORCHAS PARPADEAN TODO SE DESMORONA"
"EL NETHER ME LLAMÓ POR MI NOMBRE Y NO SÉ CÓMO SALIR DE AQUÍ"
"LOS GHAST LLORAN Y YO LLORO CON ELLOS QUÉ MIERDA DE VIDA"
"UN SLIME ME HA SALPICADO Y CREO QUE ERA VENENO PARA EL ALMA"
"AQUÍ NO HAY DÍAS SOLO UN RELOJ QUE SE BURLA DE MI CARA"
"HE CONSTRUÍDO UNA CASA Y SE HA DERRUMBADO SOLA QUÉ COÑO PASA"
"EL AIRE HUELE A AZUFRE Y A SUEÑOS ROTOS NO RESPIRO BIEN"
"UN ENDERMAN ME MIRÓ Y SENTÍ QUE ME ROBABA EL JUICIO"
"LAS OVEJAS BALAN COMO SI ME INSULTARAN ESTOY HARTO"
"CAVÉ UN TÚNEL Y AL FINAL ESTABA MI PROPIA TUMBA QUÉ LOCURA"
"EL SILENCIO ME APLASTA LOS BLOQUES ME ODIAN TODO ES GRIS"
"HE INTENTADO PESCAR Y EL AGUA ME HA ESCUPIDO A LA CARA"
"LA NOCHE DURA ETERNAMENTE Y LAS ESTRELLAS ME DAN LA ESPALDA"
"UN BLAZE ME DISPARÓ Y JURO QUE OÍ MI NOMBRE EN EL FUEGO"
"MIS MANOS SANGRAN EL PICO SE DOBLA Y EL SUELO ME ESCUPE"
"HE VISTO MI SOMBRA BAILANDO SOLA ESTE SITIO ME TIENE LOCO"
"EL SERVIDOR CRUJE COMO SI SE FUERA A ROMPER Y YO CON ÉL"
"UN PIGLIN ME HA OFRECIDO ORO Y LUEGO SE HA REÍDO DE MI MISERIA"
"LA PIEDRA ME HABLA DICE QUE NO SALGA QUE ME QUEDE AQUÍ"
"HE GRITADO AL VACÍO Y EL VACÍO ME HA GRITADO MÁS FUERTE"
"MIS ANTORCHAS SE APAGAN SOLAS CREO QUE QUIEREN QUE ME PIERDA"
"UN DROWNED ME HA MIRADO Y HE SENTIDO QUE YA ESTOY MUERTO"
"EL HAMBRE ME DEVORA Y EL PAN SABE A CENIZA QUÉ ASCO"
"HE CONSTRUÍDO UN PUENTE Y SE HA CAÍDO CONMIGO ENCIMA QUÉ MIERDA"
"LAS ARAÑAS TEJEN MI NOMBRE EN SUS TELAS ESTOY ATRAPADO"
"EL ENDER DRAGON ME SUSURRA QUE ME UNA A ÉL NO SÉ QUÉ HACER"
"LA LUZ TITUBEA LAS SOMBRAS CRECEN Y YO ME HAGO PEQUEÑO"
"HE CAVADO TANTO QUE HE ENCONTRADO MI PROPIA DESESPERACIÓN"
"EL SUELO TIEMBLA LAS PAREDES SUDAN ESTE SITIO SE HUNDE"
"UN PHANTOM ME PERSIGUE Y DICE QUE NO DUERMA NUNCA MÁS"
"MIS HERRAMIENTAS SE ROMPEN SOLAS COMO SI ME ODIARAN"
"HE VISTO UN PUEBLO ABANDONADO Y LOS ALDEANOS ERAN YO"
"LA NIEBLA ME ABRAZA Y ME DICE QUE NO HAY SALIDA QUÉ FRÍO"
"UN CREEPER EXPLOTÓ Y JURO QUE ME DIJO HASTA LUEGO"
"MIS PASOS RESUENAN COMO SI ALGUIEN ME SIGUIERA ESTOY PARANOICO"
"HE INTENTADO DORMIR Y LA CAMA ME HA ECHADO AL SUELO"
"EL CIELO ESTÁ VACÍO LAS NUBES SE RÍEN Y YO ME PUDRO AQUÍ"
"UN ZOMBIE ME HA DADO UN MORDISCO Y SABE A DERROTA"
"LAS ANTORCHAS PARPADEAN COMO SI ME GUIÑARAN UN OJO MALO"
"HE CAVADO UN POZO Y EL AGUA ME HA MIRADO CON DESPRECIO"
"EL SERVIDOR GIME LOS BLOQUES CAEN Y YO CAIGO CON ELLOS"
"UN ESQUELETO DISPARÓ Y LA FLECHA TRAÍA MI NOMBRE ESCRITO"
"LA PIEDRA HUELE A MOHO Y A PROMESAS ROTAS QUÉ MIERDA"
"HE VISTO UN PORTAL Y AL CRUZARLO ESTABA DE VUELTA AQUÍ"
"MIS MANOS TIEMBLAN EL AIRE PESA Y LA LOCURA ME GANA"
"UN POLLO ME HA PICOTEADO Y CREO QUE ERA EL DIABLO DISFRAZADO"
"EL HORIZONTE SE DOBLA LAS MONTAÑAS ME GRITAN ESTOY PERDIDO"
"HE INTENTADO ESCAPAR Y EL SERVIDOR ME HA TRAGADO OTRA VEZ"
"LA LAVA CANTA NANAS MIENTRAS ME QUEMA QUÉ JODIDA IRONÍA"
"UN SLIME ME HA HABLADO Y ME HA DICHO QUE ME RINDA YA"
"MIS DÍAS SON UN BUCLE DE BLOQUES Y GRITOS EN MI CABEZA"
"HE VISTO MI CARA EN UN CRISTAL Y NO ERA YO QUÉ COÑO"
"EL VIENTO DEL NETHER ME SUSURRA QUE ME QUEDE PARA SIEMPRE"
"UN BLAZE ME HA QUEMADO Y HE SENTIDO QUE ERA MI DESTINO"
"LAS PAREDES SE CIERRAN EL TECHO BAJA Y YO ME AHOGO"
"HE PESCADO UN ZAPATO Y ME HA MIRADO CON PENA"
"LA NOCHE ME ABRAZA Y ME DICE QUE NO HAY MAÑANA"
"UN ENDERMAN ME HA ROBADO UN BLOQUE Y MI CORDURA CON ÉL"
"EL SUELO SE AGRIETA LA LOCURA SE CUELA Y YO ME ROMPO"
"HE GRITADO AYUDA Y EL ECO ME HA DICHO ESTÁS SOLO"
"MIS ANTORCHAS HUMEAN COMO SI LLORARAN POR MÍ QUÉ TRISTE"
"UN ZOMBIE ME HA ABRAZADO Y ME HA DICHO QUE ME QUEDE"
"LA PIEDRA ME APLASTA EL AIRE ME FALTA EL SERVIDOR GANA"
"HE VISTO UN DIAMANTE Y SE HA CONVERTIDO EN CARBÓN AL TOCARLO"
"MIS DEDOS SANGRAN MIS OJOS LLORAN Y EL JUEGO SE RÍE"
"UN CREEPER ME HA EXPLOTADO CERCA Y HE OÍDO MI RISA"
"EL SERVIDOR TIEMBLA COMO SI QUISIERA ESCUPIRME FUERA"
"UN PHANTOM ME HA SUSURRADO QUE NO HAY ESPERANZA"
"LA OSCURIDAD ME COME LOS BLOQUES ME ENTIERRAN ESTOY ACABADO"
"HE CAVADO UN AGUJERO Y HE CAÍDO EN MI PROPIA MENTE"
"EL AIRE HUELE A AZUFRE Y A MI PROPIA DERROTA QUÉ PESTE"
"UN PIGLIN ME HA MIRADO Y HA ESCUPIDO A MI SOMBRA"
"LAS ANTORCHAS CHISPORROTEAN COMO SI CONSPIRARAN CONTRA MÍ"
"HE CONSTRUÍDO UNA TORRE Y SE HA CAÍDO RIÉNDOSE DE MÍ"
"EL NETHER ME ABRAZA Y ME DICE QUE NO HAY VUELTA ATRÁS"
"UN ESQUELETO ME HA DISPARADO Y LA FLECHA OLÍA A MIEDO"
"MIS PULMONES ARDEN MIS MANOS FALLAN Y EL JUEGO ME ODIA"
"HE VISTO UN ALDEANO Y ERA MI CARA GRITÁNDOME HUYE"
"LA LAVA ME LLAMA EL VACÍO ME TIENTA Y YO ME PIERDO"
"UN SLIME ME HA APLASTADO Y HE SENTIDO QUE ERA MI FIN"
"EL SERVIDOR SE DESANGRA YO ME DESHAGO Y TODO SE PUDRE"
)

# Frase por defecto si no hay jugadores conectados
FRASE_DEFECTO="Parece que no hay nadie en el servidor y ahora a quien cojones insulto yo"

# Obtener lista de jugadores conectados usando el comando de Minecraft
JUGADORES=$(docker exec $DOCKER_CONTAINER rcon-cli list | sed -n 's/^.*players online://p')

# Verificar si hay jugadores conectados
if [ -z "$JUGADORES" ]; then
    # No hay jugadores conectados
    MENSAJE="$FRASE_DEFECTO"
else
    # Convertir la lista de jugadores en un array
    IFS=',' read -ra LISTA_JUGADORES <<< "$JUGADORES"
    # Seleccionar jugador aleatorio
    JUGADOR=${LISTA_JUGADORES[RANDOM % ${#LISTA_JUGADORES[@]}]}
    JUGADOR=$(echo $JUGADOR | xargs)  # Eliminar espacios
    # Seleccionar frase aleatoria e insertar el nombre del jugador
    FRASE=${FRASES[RANDOM % ${#FRASES[@]}]}
    MENSAJE=$(printf "$FRASE" "$JUGADOR")
fi

# Enviar el mensaje al servidor de Minecraft usando rcon-cli

docker exec $DOCKER_CONTAINER rcon-cli "say $MENSAJE"
